service: aws-lambda-mmbc-yahoo
frameworkVersion: '3'
plugins:
  - serverless-offline

provider:
  name: aws
  region: us-west-1
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
